pull_request_rules:
  - name: Auto-rebase if appropriately labeled or if the author is an authorized bot
    conditions:
      - or:
        - label=auto-update-rebase
        - and:
            - label=dependencies
            - or: &authors_are_bots
                - author=renovate[bot]
                - author=dependabot[bot]
      - -draft
      - -conflict
    actions:
      rebase:
  - name: Auto-update with merge if appropriately labeled
    conditions:
      - label=auto-update-merge
      - -draft
      - -conflict
    actions:
      update:
  - name: rebase-merge working updates
    conditions:
      - and:
        - or: *authors_are_bots
        - and:
          - or:
            - check-success=ci-cd / success
            - check-neutral=ci-cd / success
            - check-skipped=ci-cd / success
          - "#review-threads-unresolved=0"
          - "#commits-behind=0"
      - label=dependencies
      - -draft
      - -conflict
    actions:
      merge:
        method: rebase
  - name: ask to resolve conflict
    conditions:
      - conflict
    actions:
      comment:
        message: |
          Hi @{{author}}! :wave:
          This pull request has conflicts :confounded:
          Could you fix it? :wrench:
          Thank you! :pray:
